export const CONNECTION_UPDATING = 'CONNECTION_UPDATING'
export const CONNECTION_SUCCESS = 'CONNECTION_SUCCESS'
export const CONNECTION_ERROR = 'CONNECTION_ERROR'

export const PART_SUCCESS = 'PART_SUCCESS'
export const PART_ERROR = 'PART_ERROR'
